apiVersion: v2
name: pagopacruscottosertbackend
description: Microservice description
type: application
version: 0.276.0
appVersion: 0.10.0-1-features-openapi-subkey
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
