apiVersion: v2
name: pagopacruscottosertbackend
description: Microservice description
type: application
version: 0.268.0
appVersion: 0.9.2-1-features/manage-table-anagag-intermediario
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
