apiVersion: v2
name: pagopacruscottosertbackend
description: Microservice description
type: application
version: 0.272.0
appVersion: 0.9.2-5-features-openapi
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
